name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: get_gcc-arm
      run: sudo apt-get install gcc-arm-none-eabi
    - name: main
      run: make CC=arm-none-eabi-gcc
    - name: groundstation
      run: cd groundstation && make
    - name: upload compiled file artifact
      uses: actions/upload-artifact@v4
      with:
          name: libADCS.a
          path: libADCS.a
